name: unsplash_clone
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  animated_svg: ^2.1.0
  app_links: ^6.4.1
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8
  d_method: ^0.2.6
  device_preview: ^1.3.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  http: ^1.5.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  midtrans_sdk: ^1.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  slide_to_act: ^2.0.2
  supabase_flutter: ^2.9.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.13.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/sounds/ # ‚Üê TAMBAHAN BARU
    - assets/midtrans_webview.html

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
